apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bulinbot-data-pvc
  namespace: bulinbot-standalone-ns
  labels:
    app: bulinbot-standalone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard # uncomment and set proper StorageClass