apiVersion: v1
kind: Service
metadata:
  name: bulinbot-service-lb
  namespace: bulinbot-ns
  labels:
    app: bulinbot-stack
spec:
  type: LoadBalancer
  selector:
    app: bulinbot-stack
  ports:
    - name: napcat-web
      port: 6099
      targetPort: 6099
    - name: bulinbot-web
      port: 6185
      targetPort: 6185